<footer class:foot>
    <div class="footer-grid">
      <div class="footer-info">
        <p><strong>GameX Studios</strong></p>
        <p>Kuala Lumpur, Selangor, Malaysia</p>
      </div>
      <div class="footer-links-container">
        <ul class="footer-links">
          <li><a href="https://github.com/ChanJayShen/Web_project.git" target=_blank>GitHub</a></li>
          <li><a
              href="https://student-team-jr2tz4wq.atlassian.net/jira/software/projects/WP/list?jql=project+%3D+WP+ORDER+BY+cf%5B10019%5D+ASC&atlOrigin=eyJpIjoiYjllNDBiZWZmNjliNGYyZjk2ZTg0MWZmMDQyYzMyNWQiLCJwIjoiaiJ9 "
              target=_blank>Jira</a></li>
          <li><a href="mailto:info@GameXStudios.com" target=_blank>Contact Us</a></li>
          <li><a href="login.php">Manager Portal</a></li>
        </ul>
      </div>
    </div>
    <p class="copyright">&copy; 2026 GameX Studios. All rights reserved.</p>
  </footer>